tunnel: 609fe7fb-d511-4d68-a303-39bafd3da360
credentials-file: /home/karmean/.cloudflared/609fe7fb-d511-4d68-a303-39bafd3da360.json

ingress:
  - hostname: api.kraveapi.xyz
    service: http://localhost:8000
  - service: http_status:404
