tunnel: 53ecdfb4-a2bf-4797-bdec-e0de68d9536d
credentials-file: /home/karmean/.cloudflared/53ecdfb4-a2bf-4797-bdec-e0de68d9536d.json

ingress:
  - hostname: api.kraveapi.xyz
    service: http://localhost:8000
  - service: http_status:404
