tunnel: 9477541f-c461-4ee3-9876-eb8bf3740a12
credentials-file: /home/karmean/.cloudflared/9477541f-c461-4ee3-9876-eb8bf3740a12.json

ingress:
  - hostname: api.kraveapi.xyz
    service: http://localhost:8000
  - service: http_status:404
