services:
  - type: web
    name: instagram-backend    # Nombre del servicio en Render
    env: docker
    plan: free                 # Plan de Render (free tier)
    region: oregon             # Región de despliegue (puede ajustarse según preferencia)
    dockerfilePath: ./Dockerfile
    # Ruta del contexto de Docker (opcional, por defecto es el directorio actual)
    dockerContext: .
    envVars:
      - key: INSTAGRAM_USER
        fromSecret: instagram_user    # Referencia a un secreto definido con el usuario de IG
      - key: INSTAGRAM_PASS
        fromSecret: instagram_pass    # Referencia a un secreto definido con la contraseña de IG
      - key: OPENAI_API_KEY
        fromSecret: openai_api_key    # API Key de OpenAI
      - key: BITLY_TOKEN
        fromSecret: bitly_token       # Token API de Bitly
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PORT
        value: "3000"
