services:
  - type: web
    name: kraveai-backend
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true  # ⬅️ Recomendado si quieres que se actualice con cada push

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false  # ⬅️ Protege tu clave en GitHub, Render la pedirá desde el dashboard
      - key: BITLY_TOKEN
        sync: false
      - key: IG_USER
        sync: false
      - key: IG_PASS
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
