services:
  - type: web
    name: kraveai-backend
    env: docker
    plan: starter  # Cambia a 'pro' si estás usando Pro Ultra
    autoDeploy: true
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: IG_USER
        value: tu_usuario_instagram
      - key: IG_PASS
        value: tu_contraseña_instagram
      - key: OPENAI_API_KEY
        value: sk-xxxxx
      - key: BITLY_TOKEN
        value: tu_token_bitly
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PORT
        value: 3000
