# render.yaml
buildCommand: |
  # Descargar Chromium en la raíz del proyecto
  curl -LO https://github.com/Sparticuz/chromium/releases/download/v125.0.0/chromium-v125.0.0-pack.tar
  tar xf chromium-v125.0.0-pack.tar -C .  # Extraer en directorio actual
  chmod +x chrome
  mkdir -p chromium
  mv chrome chromium/  # Mover a subdirectorio
  npm install
